/* automatically generated by rust-bindgen 0.59.2 */

pub const NISYSCFG_SIMPLE_STRING_LENGTH: u32 = 1024;
pub const NISYSCFG_REBOOT_DEFAULT_TIMEOUT_MSEC: u32 = 180000;
pub const NISYSCFG_REMOTE_DEFAULT_TIMEOUT_MSEC: u32 = 300000;
pub type va_list = __builtin_va_list;
pub const NISysCfgStatus_NISysCfg_OK: NISysCfgStatus = 0;
pub const NISysCfgStatus_NISysCfg_EndOfEnum: NISysCfgStatus = 1;
pub const NISysCfgStatus_NISysCfg_SelfTestBasicOnly: NISysCfgStatus = 263024;
pub const NISysCfgStatus_NISysCfg_FoundCachedOfflineSystem: NISysCfgStatus = 263168;
pub const NISysCfgStatus_NISysCfg_RestartLocalhostInitiated: NISysCfgStatus = 263169;
pub const NISysCfgStatus_NISysCfg_ChangedPropertyNotSaved: NISysCfgStatus = 263170;
pub const NISysCfgStatus_NISysCfg_NotImplemented: NISysCfgStatus = -2147467263;
pub const NISysCfgStatus_NISysCfg_NullPointer: NISysCfgStatus = -2147467261;
pub const NISysCfgStatus_NISysCfg_Fail: NISysCfgStatus = -2147467259;
pub const NISysCfgStatus_NISysCfg_Unexpected: NISysCfgStatus = -2147418113;
pub const NISysCfgStatus_NISysCfg_OutOfMemory: NISysCfgStatus = -2147024882;
pub const NISysCfgStatus_NISysCfg_InvalidArg: NISysCfgStatus = -2147024809;
pub const NISysCfgStatus_NISysCfg_OperationTimedOut: NISysCfgStatus = -2147220448;
pub const NISysCfgStatus_NISysCfg_FileNotFound: NISysCfgStatus = -2147220322;
pub const NISysCfgStatus_NISysCfg_InvalidMACFormat: NISysCfgStatus = -2147220278;
pub const NISysCfgStatus_NISysCfg_PropMismatch: NISysCfgStatus = -2147220624;
pub const NISysCfgStatus_NISysCfg_PropDoesNotExist: NISysCfgStatus = -2147220623;
pub const NISysCfgStatus_NISysCfg_UriIllegalSyntax: NISysCfgStatus = -2147220622;
pub const NISysCfgStatus_NISysCfg_UriTargetDoesNotExist: NISysCfgStatus = -2147220621;
pub const NISysCfgStatus_NISysCfg_UriExpertDoesNotExist: NISysCfgStatus = -2147220620;
pub const NISysCfgStatus_NISysCfg_ItemDoesNotExist: NISysCfgStatus = -2147220619;
pub const NISysCfgStatus_NISysCfg_InvalidMode: NISysCfgStatus = -2147220618;
pub const NISysCfgStatus_NISysCfg_SysConfigAPINotInstalled: NISysCfgStatus = -2147220616;
pub const NISysCfgStatus_NISysCfg_NameSyntaxIllegal: NISysCfgStatus = -2147220614;
pub const NISysCfgStatus_NISysCfg_NameCollision: NISysCfgStatus = -2147220613;
pub const NISysCfgStatus_NISysCfg_NoPropValidated: NISysCfgStatus = -2147220612;
pub const NISysCfgStatus_NISysCfg_UriUnauthorized: NISysCfgStatus = -2147220611;
pub const NISysCfgStatus_NISysCfg_RenameResourceDependencies: NISysCfgStatus = -2147220610;
pub const NISysCfgStatus_NISysCfg_ValueInvalid: NISysCfgStatus = -2147220609;
pub const NISysCfgStatus_NISysCfg_ValuesInconsistent: NISysCfgStatus = -2147220608;
pub const NISysCfgStatus_NISysCfg_Canceled: NISysCfgStatus = -2147220607;
pub const NISysCfgStatus_NISysCfg_ResponseSyntax: NISysCfgStatus = -2147220606;
pub const NISysCfgStatus_NISysCfg_ResourceIsNotPresent: NISysCfgStatus = -2147220605;
pub const NISysCfgStatus_NISysCfg_ResourceIsSimulated: NISysCfgStatus = -2147220604;
pub const NISysCfgStatus_NISysCfg_NotInFirmwareUpdateState: NISysCfgStatus = -2147220603;
pub const NISysCfgStatus_NISysCfg_FirmwareImageDeviceMismatch: NISysCfgStatus = -2147220602;
pub const NISysCfgStatus_NISysCfg_FirmwareImageCorrupt: NISysCfgStatus = -2147220601;
pub const NISysCfgStatus_NISysCfg_InvalidFirmwareVersion: NISysCfgStatus = -2147220600;
pub const NISysCfgStatus_NISysCfg_OlderFirmwareVersion: NISysCfgStatus = -2147220599;
pub const NISysCfgStatus_NISysCfg_InvalidLoginCredentials: NISysCfgStatus = -2147220598;
pub const NISysCfgStatus_NISysCfg_FirmwareUpdateAttemptFailed: NISysCfgStatus = -2147220597;
pub const NISysCfgStatus_NISysCfg_EncryptionFailed: NISysCfgStatus = -2147220596;
pub const NISysCfgStatus_NISysCfg_SomePropsNotValidated: NISysCfgStatus = -2147220595;
pub const NISysCfgStatus_NISysCfg_InvalidCalibrationCredentials: NISysCfgStatus = -2147220594;
pub const NISysCfgStatus_NISysCfg_CannotDeletePresentResource: NISysCfgStatus = -2147220593;
pub const NISysCfgStatus_NISysCfg_UriTargetTransmitError: NISysCfgStatus = -2147220592;
pub const NISysCfgStatus_NISysCfg_DecryptionFailed: NISysCfgStatus = -2147220591;
pub const NISysCfgStatus_NISysCfg_FirmwareExpertVersionMismatch: NISysCfgStatus = -2147220590;
pub const NISysCfgStatus_NISysCfg_AmbiguousImportAction: NISysCfgStatus = -2147220589;
pub const NISysCfgStatus_NISysCfg_RequiredItemFailedImport: NISysCfgStatus = -2147220588;
pub const NISysCfgStatus_NISysCfg_ItemInUse: NISysCfgStatus = -2147220587;
pub const NISysCfgStatus_NISysCfg_ItemTypeNotSupported: NISysCfgStatus = -2147220586;
pub const NISysCfgStatus_NISysCfg_PermissionDenied: NISysCfgStatus = -2147220560;
pub const NISysCfgStatus_NISysCfg_SystemNotFound: NISysCfgStatus = -2147220559;
pub const NISysCfgStatus_NISysCfg_TransformFailed: NISysCfgStatus = -2147220558;
pub const NISysCfgStatus_NISysCfg_NotInstalled: NISysCfgStatus = -2147220557;
pub const NISysCfgStatus_NISysCfg_LaunchFailure: NISysCfgStatus = -2147220556;
pub const NISysCfgStatus_NISysCfg_InternalTimeout: NISysCfgStatus = -2147220555;
pub const NISysCfgStatus_NISysCfg_MissingTransform: NISysCfgStatus = -2147220554;
pub const NISysCfgStatus_NISysCfg_IncorrectExtension: NISysCfgStatus = -2147220553;
pub const NISysCfgStatus_NISysCfg_FileReadOnly: NISysCfgStatus = -2147220552;
pub const NISysCfgStatus_NISysCfg_ReportOverwrite: NISysCfgStatus = -2147220551;
pub const NISysCfgStatus_NISysCfg_DirectoryError: NISysCfgStatus = -2147220550;
pub const NISysCfgStatus_NISysCfg_CannotOpenFile: NISysCfgStatus = -2147220480;
pub const NISysCfgStatus_NISysCfg_InsufficientPermissions: NISysCfgStatus = -2147220479;
pub const NISysCfgStatus_NISysCfg_NCECopierFailed: NISysCfgStatus = -2147220478;
pub const NISysCfgStatus_NISysCfg_FileOperationFailed: NISysCfgStatus = -2147220477;
pub const NISysCfgStatus_NISysCfg_NameCollisionError: NISysCfgStatus = -2147220476;
pub const NISysCfgStatus_NISysCfg_UnexpectedError: NISysCfgStatus = -2147220475;
pub const NISysCfgStatus_NISysCfg_NCENoStreamError: NISysCfgStatus = -2147220474;
pub const NISysCfgStatus_NISysCfg_NCECompressionError: NISysCfgStatus = -2147220473;
pub const NISysCfgStatus_NISysCfg_NCEStreamReadError: NISysCfgStatus = -2147220472;
pub const NISysCfgStatus_NISysCfg_NCEStreamWriteError: NISysCfgStatus = -2147220471;
pub const NISysCfgStatus_NISysCfg_NCEStreamSeekError: NISysCfgStatus = -2147220470;
pub const NISysCfgStatus_NISysCfg_NCERepoNotReady: NISysCfgStatus = -2147220469;
pub const NISysCfgStatus_NISysCfg_NCERepoInvalid: NISysCfgStatus = -2147220468;
pub const NISysCfgStatus_NISysCfg_NCERepoIncompat: NISysCfgStatus = -2147220467;
pub const NISysCfgStatus_NISysCfg_NCENoImportStorage: NISysCfgStatus = -2147220466;
pub const NISysCfgStatus_NISysCfg_NCENoExportStorage: NISysCfgStatus = -2147220465;
pub const NISysCfgStatus_NISysCfg_NCENoObjCopier: NISysCfgStatus = -2147220464;
pub const NISysCfgStatus_NISysCfg_CopyInProgress: NISysCfgStatus = -2147220463;
pub const NISysCfgStatus_NISysCfg_FileNotRecognized: NISysCfgStatus = -2147220462;
pub const NISysCfgStatus_NISysCfg_SystemNotSupported: NISysCfgStatus = -2147220461;
pub const NISysCfgStatus_NISysCfg_SystemNotReachable: NISysCfgStatus = -2147220460;
pub const NISysCfgStatus_NISysCfg_ProductSoftwareNotInstalled: NISysCfgStatus = -2147220459;
pub const NISysCfgStatus_NISysCfg_ProductSoftwareTooOld: NISysCfgStatus = -2147220458;
pub const NISysCfgStatus_NISysCfg_ProductSoftwareTooNew: NISysCfgStatus = -2147220457;
pub const NISysCfgStatus_NISysCfg_DataTooOld: NISysCfgStatus = -2147220456;
pub const NISysCfgStatus_NISysCfg_DataTooNew: NISysCfgStatus = -2147220455;
pub const NISysCfgStatus_NISysCfg_NoItemsToCopy: NISysCfgStatus = -2147220454;
pub const NISysCfgStatus_NISysCfg_OrphanItems: NISysCfgStatus = -2147220453;
pub const NISysCfgStatus_NISysCfg_DirtyItems: NISysCfgStatus = -2147220452;
pub const NISysCfgStatus_NISysCfg_FileOverwrite: NISysCfgStatus = -2147220451;
pub const NISysCfgStatus_NISysCfg_ItemOverwrite: NISysCfgStatus = -2147220450;
pub const NISysCfgStatus_NISysCfg_MissingDependency: NISysCfgStatus = -2147220449;
pub const NISysCfgStatus_NISysCfg_OperationCanceled: NISysCfgStatus = -2147220447;
pub const NISysCfgStatus_NISysCfg_WarningConflicts: NISysCfgStatus = -2147220446;
pub const NISysCfgStatus_NISysCfg_ErrorConflicts: NISysCfgStatus = -2147220445;
pub const NISysCfgStatus_NISysCfg_ItemsRequireUserInput: NISysCfgStatus = -2147220444;
pub const NISysCfgStatus_NISysCfg_ProductExpertNotReady: NISysCfgStatus = -2147220443;
pub const NISysCfgStatus_NISysCfg_OrphanFiles: NISysCfgStatus = -2147220442;
pub const NISysCfgStatus_NISysCfg_IsConst: NISysCfgStatus = -2147220441;
pub const NISysCfgStatus_NISysCfg_UnsupportedProductMode: NISysCfgStatus = -2147220440;
pub const NISysCfgStatus_NISysCfg_HostSoftwareTooOld: NISysCfgStatus = -2147220385;
pub const NISysCfgStatus_NISysCfg_OpkgUpdateFeedFailure: NISysCfgStatus = -2147220384;
pub const NISysCfgStatus_NISysCfg_FeedNotFound: NISysCfgStatus = -2147220383;
pub const NISysCfgStatus_NISysCfg_FeedAlreadyExists: NISysCfgStatus = -2147220382;
pub const NISysCfgStatus_NISysCfg_InstallOptionNotSupported: NISysCfgStatus = -2147220381;
pub const NISysCfgStatus_NISysCfg_FirmwareTooOld: NISysCfgStatus = -2147220380;
pub const NISysCfgStatus_NISysCfg_SoftwareTooOld: NISysCfgStatus = -2147220379;
pub const NISysCfgStatus_NISysCfg_RequiresSSH: NISysCfgStatus = -2147220378;
pub const NISysCfgStatus_NISysCfg_OpkgResponseSyntax: NISysCfgStatus = -2147220377;
pub const NISysCfgStatus_NISysCfg_WrongSoftwareSetType: NISysCfgStatus = -2147220376;
pub const NISysCfgStatus_NISysCfg_RequiresOpkg: NISysCfgStatus = -2147220375;
pub const NISysCfgStatus_NISysCfg_HDFormatEncryptNotSupported: NISysCfgStatus = -2147220374;
pub const NISysCfgStatus_NISysCfg_HDFormatNoRecoveryKeyDevice: NISysCfgStatus = -2147220373;
pub const NISysCfgStatus_NISysCfg_RestartLocalhostAmbiguous: NISysCfgStatus = -2147220372;
pub const NISysCfgStatus_NISysCfg_ImageInvalidCorrupt: NISysCfgStatus = -2147220371;
pub const NISysCfgStatus_NISysCfg_SafeOrInstallModeRequired: NISysCfgStatus = -2147220370;
pub const NISysCfgStatus_NISysCfg_EncryptPhraseMismatch: NISysCfgStatus = -2147220369;
pub const NISysCfgStatus_NISysCfg_InvalidIP: NISysCfgStatus = -2147220368;
pub const NISysCfgStatus_NISysCfg_InvalidGateway: NISysCfgStatus = -2147220367;
pub const NISysCfgStatus_NISysCfg_InvalidDNS: NISysCfgStatus = -2147220366;
pub const NISysCfgStatus_NISysCfg_InvalidSubnet: NISysCfgStatus = -2147220365;
pub const NISysCfgStatus_NISysCfg_CmdNotSupported: NISysCfgStatus = -2147220364;
pub const NISysCfgStatus_NISysCfg_ConfigFailed: NISysCfgStatus = -2147220363;
pub const NISysCfgStatus_NISysCfg_Locked: NISysCfgStatus = -2147220362;
pub const NISysCfgStatus_NISysCfg_BadPassword: NISysCfgStatus = -2147220361;
pub const NISysCfgStatus_NISysCfg_NotConfigurable: NISysCfgStatus = -2147220360;
pub const NISysCfgStatus_NISysCfg_UnlockFailed: NISysCfgStatus = -2147220359;
pub const NISysCfgStatus_NISysCfg_LockFailed: NISysCfgStatus = -2147220358;
pub const NISysCfgStatus_NISysCfg_InstallFailed: NISysCfgStatus = -2147220357;
pub const NISysCfgStatus_NISysCfg_InstallationCorrupt: NISysCfgStatus = -2147220356;
pub const NISysCfgStatus_NISysCfg_EmptyFile: NISysCfgStatus = -2147220355;
pub const NISysCfgStatus_NISysCfg_UnconfiguredIP: NISysCfgStatus = -2147220354;
pub const NISysCfgStatus_NISysCfg_InstallationGenericFailure: NISysCfgStatus = -2147220352;
pub const NISysCfgStatus_NISysCfg_DownloadAlreadyStarted: NISysCfgStatus = -2147220350;
pub const NISysCfgStatus_NISysCfg_Aborted: NISysCfgStatus = -2147220349;
pub const NISysCfgStatus_NISysCfg_DiskFull: NISysCfgStatus = -2147220338;
pub const NISysCfgStatus_NISysCfg_HDFormatFailed: NISysCfgStatus = -2147220337;
pub const NISysCfgStatus_NISysCfg_HDFormatNotSafeMode: NISysCfgStatus = -2147220336;
pub const NISysCfgStatus_NISysCfg_HDFormatRebootFailed: NISysCfgStatus = -2147220335;
pub const NISysCfgStatus_NISysCfg_ConnectionRefused: NISysCfgStatus = -2147220334;
pub const NISysCfgStatus_NISysCfg_GetRemoteFilesFailed: NISysCfgStatus = -2147220331;
pub const NISysCfgStatus_NISysCfg_PutRemoteFilesFailed: NISysCfgStatus = -2147220330;
pub const NISysCfgStatus_NISysCfg_InvalidImage: NISysCfgStatus = -2147220329;
pub const NISysCfgStatus_NISysCfg_ImageDeviceCodeMismatch: NISysCfgStatus = -2147220328;
pub const NISysCfgStatus_NISysCfg_SystemMismatch: NISysCfgStatus = -2147220327;
pub const NISysCfgStatus_NISysCfg_HDFormatWrongFS: NISysCfgStatus = -2147220326;
pub const NISysCfgStatus_NISysCfg_CustomInstallNotSupported: NISysCfgStatus = -2147220325;
pub const NISysCfgStatus_NISysCfg_FTPFailed: NISysCfgStatus = -2147220324;
pub const NISysCfgStatus_NISysCfg_Timeout: NISysCfgStatus = -2147220323;
pub const NISysCfgStatus_NISysCfg_DirNotFound: NISysCfgStatus = -2147220321;
pub const NISysCfgStatus_NISysCfg_PathNotFound: NISysCfgStatus = -2147220320;
pub const NISysCfgStatus_NISysCfg_NoSoftwareAvailable: NISysCfgStatus = -2147220319;
pub const NISysCfgStatus_NISysCfg_OverwriteError: NISysCfgStatus = -2147220318;
pub const NISysCfgStatus_NISysCfg_HDFormatCannotKeepCfg: NISysCfgStatus = -2147220317;
pub const NISysCfgStatus_NISysCfg_FileOrPathTooLong: NISysCfgStatus = -2147220316;
pub const NISysCfgStatus_NISysCfg_DDPInternalTimeout: NISysCfgStatus = -2147220315;
pub const NISysCfgStatus_NISysCfg_IOPermissionDenied: NISysCfgStatus = -2147220314;
pub const NISysCfgStatus_NISysCfg_PathAlreadyExists: NISysCfgStatus = -2147220313;
pub const NISysCfgStatus_NISysCfg_ExecutionFailure: NISysCfgStatus = -2147220312;
pub const NISysCfgStatus_NISysCfg_DownloadError: NISysCfgStatus = -2147220311;
pub const NISysCfgStatus_NISysCfg_NetSendFailed: NISysCfgStatus = -2147220309;
pub const NISysCfgStatus_NISysCfg_ContactHostDisconnected: NISysCfgStatus = -2147220308;
pub const NISysCfgStatus_NISysCfg_NetSvcDown: NISysCfgStatus = -2147220307;
pub const NISysCfgStatus_NISysCfg_NotConfirmed: NISysCfgStatus = -2147220306;
pub const NISysCfgStatus_NISysCfg_HostNotResolved: NISysCfgStatus = -2147220305;
pub const NISysCfgStatus_NISysCfg_RebootTimeout: NISysCfgStatus = -2147220304;
pub const NISysCfgStatus_NISysCfg_NoConfirmationFP1600: NISysCfgStatus = -2147220303;
pub const NISysCfgStatus_NISysCfg_DuplicateStartup: NISysCfgStatus = -2147220300;
pub const NISysCfgStatus_NISysCfg_RemoteInvalidArgument: NISysCfgStatus = -2147220299;
pub const NISysCfgStatus_NISysCfg_NotUninstallable: NISysCfgStatus = -2147220298;
pub const NISysCfgStatus_NISysCfg_DuplicatesNotAllowed: NISysCfgStatus = -2147220297;
pub const NISysCfgStatus_NISysCfg_NotInstallable: NISysCfgStatus = -2147220296;
pub const NISysCfgStatus_NISysCfg_WrongDevice: NISysCfgStatus = -2147220295;
pub const NISysCfgStatus_NISysCfg_WrongOS: NISysCfgStatus = -2147220294;
pub const NISysCfgStatus_NISysCfg_OSVersionTooOld: NISysCfgStatus = -2147220293;
pub const NISysCfgStatus_NISysCfg_IOError: NISysCfgStatus = -2147220292;
pub const NISysCfgStatus_NISysCfg_CorruptConfig: NISysCfgStatus = -2147220291;
pub const NISysCfgStatus_NISysCfg_BufferOverflow: NISysCfgStatus = -2147220290;
pub const NISysCfgStatus_NISysCfg_UnsupportedCDFVersion: NISysCfgStatus = -2147220289;
pub const NISysCfgStatus_NISysCfg_InvalidStack: NISysCfgStatus = -2147220288;
pub const NISysCfgStatus_NISysCfg_IncompleteStack: NISysCfgStatus = -2147220287;
pub const NISysCfgStatus_NISysCfg_StackItemMissing: NISysCfgStatus = -2147220286;
pub const NISysCfgStatus_NISysCfg_TopLevelHiddenComponentError: NISysCfgStatus = -2147220285;
pub const NISysCfgStatus_NISysCfg_InvalidAddon: NISysCfgStatus = -2147220284;
pub const NISysCfgStatus_NISysCfg_NoRTImagesFolder: NISysCfgStatus = -2147220283;
pub const NISysCfgStatus_NISysCfg_NoRTImagesRegistry: NISysCfgStatus = -2147220282;
pub const NISysCfgStatus_NISysCfg_NoRTS2CDF: NISysCfgStatus = -2147220281;
pub const NISysCfgStatus_NISysCfg_UnsupportedOS: NISysCfgStatus = -2147220280;
pub const NISysCfgStatus_NISysCfg_ExactVersionRequired: NISysCfgStatus = -2147220279;
pub const NISysCfgStatus_NISysCfg_InvalidStartup: NISysCfgStatus = -2147220277;
pub type NISysCfgStatus = ::std::os::raw::c_int;
pub type NISysCfgUInt64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NISysCfgTimestampUTC {
    pub u32Data: [::std::os::raw::c_uint; 4usize],
}
#[test]
fn bindgen_test_layout_NISysCfgTimestampUTC() {
    assert_eq!(
        ::std::mem::size_of::<NISysCfgTimestampUTC>(),
        16usize,
        concat!("Size of: ", stringify!(NISysCfgTimestampUTC))
    );
    assert_eq!(
        ::std::mem::align_of::<NISysCfgTimestampUTC>(),
        4usize,
        concat!("Alignment of ", stringify!(NISysCfgTimestampUTC))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<NISysCfgTimestampUTC>())).u32Data as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(NISysCfgTimestampUTC),
            "::",
            stringify!(u32Data)
        )
    );
}
#[doc = ""]
pub type NISysCfgSessionHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgResourceHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgFilterHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgSoftwareSetHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumResourceHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumExpertHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumSystemHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumSoftwareFeedHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumSoftwareSetHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumDependencyHandle = *mut ::std::os::raw::c_void;
pub type NISysCfgEnumSoftwareComponentHandle = *mut ::std::os::raw::c_void;
pub const NISysCfgIncludeCachedResults_NISysCfgIncludeCachedResultsNone:
    NISysCfgIncludeCachedResults = 0;
pub const NISysCfgIncludeCachedResults_NISysCfgIncludeCachedResultsOnlyIfOnline:
    NISysCfgIncludeCachedResults = 1;
pub const NISysCfgIncludeCachedResults_NISysCfgIncludeCachedResultsAll:
    NISysCfgIncludeCachedResults = 3;
#[doc = ""]
pub type NISysCfgIncludeCachedResults = ::std::os::raw::c_int;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatHostname: NISysCfgSystemNameFormat = 16;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatHostnameIp: NISysCfgSystemNameFormat =
    18;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatHostnameMac: NISysCfgSystemNameFormat =
    19;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatIp: NISysCfgSystemNameFormat = 32;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatIpHostname: NISysCfgSystemNameFormat =
    33;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatIpMac: NISysCfgSystemNameFormat = 35;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatMac: NISysCfgSystemNameFormat = 48;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatMacHostname: NISysCfgSystemNameFormat =
    49;
pub const NISysCfgSystemNameFormat_NISysCfgSystemNameFormatMacIp: NISysCfgSystemNameFormat = 50;
pub type NISysCfgSystemNameFormat = ::std::os::raw::c_int;
pub const NISysCfgFileSystemMode_NISysCfgFileSystemDefault: NISysCfgFileSystemMode = 0;
pub const NISysCfgFileSystemMode_NISysCfgFileSystemFat: NISysCfgFileSystemMode = 1;
pub const NISysCfgFileSystemMode_NISysCfgFileSystemReliance: NISysCfgFileSystemMode = 2;
pub const NISysCfgFileSystemMode_NISysCfgFileSystemUBIFS: NISysCfgFileSystemMode = 16384;
pub const NISysCfgFileSystemMode_NISysCfgFileSystemExt4: NISysCfgFileSystemMode = 32768;
pub type NISysCfgFileSystemMode = ::std::os::raw::c_int;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgResetPrimaryResetOthers:
    NISysCfgNetworkInterfaceSettings = 0;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgPreservePrimaryResetOthers:
    NISysCfgNetworkInterfaceSettings = 1;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgPreservePrimaryPreserveOthers:
    NISysCfgNetworkInterfaceSettings = 2;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgPreservePrimaryApplyOthers:
    NISysCfgNetworkInterfaceSettings = 3;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgApplyPrimaryResetOthers:
    NISysCfgNetworkInterfaceSettings = 4;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgApplyPrimaryPreserveOthers:
    NISysCfgNetworkInterfaceSettings = 5;
pub const NISysCfgNetworkInterfaceSettings_NISysCfgApplyPrimaryApplyOthers:
    NISysCfgNetworkInterfaceSettings = 6;
pub type NISysCfgNetworkInterfaceSettings = ::std::os::raw::c_int;
pub const NISysCfgComponentType_NISysCfgItemTypeStandard: NISysCfgComponentType = 0;
pub const NISysCfgComponentType_NISysCfgItemTypeHidden: NISysCfgComponentType = 1;
pub const NISysCfgComponentType_NISysCfgItemTypeSystem: NISysCfgComponentType = 2;
pub const NISysCfgComponentType_NISysCfgItemTypeUnknown: NISysCfgComponentType = 3;
pub const NISysCfgComponentType_NISysCfgItemTypeStartup: NISysCfgComponentType = 4;
pub const NISysCfgComponentType_NISysCfgItemTypeImage: NISysCfgComponentType = 5;
pub const NISysCfgComponentType_NISysCfgItemTypeEssential: NISysCfgComponentType = 6;
pub type NISysCfgComponentType = ::std::os::raw::c_int;
pub const NISysCfgIncludeComponentTypes_NISysCfgIncludeItemsAllVisible:
    NISysCfgIncludeComponentTypes = 0;
pub const NISysCfgIncludeComponentTypes_NISysCfgIncludeItemsAllVisibleAndHidden:
    NISysCfgIncludeComponentTypes = 1;
pub const NISysCfgIncludeComponentTypes_NISysCfgIncludeItemsOnlyStandard:
    NISysCfgIncludeComponentTypes = 2;
pub const NISysCfgIncludeComponentTypes_NISysCfgIncludeItemsOnlyStartup:
    NISysCfgIncludeComponentTypes = 3;
pub type NISysCfgIncludeComponentTypes = ::std::os::raw::c_int;
pub const NISysCfgVersionSelectionMode_NISysCfgVersionSelectionHighest:
    NISysCfgVersionSelectionMode = 0;
pub const NISysCfgVersionSelectionMode_NISysCfgVersionSelectionExact: NISysCfgVersionSelectionMode =
    1;
pub type NISysCfgVersionSelectionMode = ::std::os::raw::c_int;
pub const NISysCfgImportMode_NISysCfgImportMergeItems: NISysCfgImportMode = 0;
pub const NISysCfgImportMode_NISysCfgImportDeleteConfigFirst: NISysCfgImportMode = 1048576;
pub const NISysCfgImportMode_NISysCfgImportPreserveConflictItems: NISysCfgImportMode = 2097152;
pub type NISysCfgImportMode = ::std::os::raw::c_int;
pub const NISysCfgReportType_NISysCfgReportXml: NISysCfgReportType = 0;
pub const NISysCfgReportType_NISysCfgReportHtml: NISysCfgReportType = 1;
pub const NISysCfgReportType_NISysCfgReportTechnicalSupportZip: NISysCfgReportType = 2;
pub type NISysCfgReportType = ::std::os::raw::c_int;
pub const NISysCfgBusType_NISysCfgBusTypeBuiltIn: NISysCfgBusType = 0;
pub const NISysCfgBusType_NISysCfgBusTypePciPxi: NISysCfgBusType = 1;
pub const NISysCfgBusType_NISysCfgBusTypeUsb: NISysCfgBusType = 2;
pub const NISysCfgBusType_NISysCfgBusTypeGpib: NISysCfgBusType = 3;
pub const NISysCfgBusType_NISysCfgBusTypeVxi: NISysCfgBusType = 4;
pub const NISysCfgBusType_NISysCfgBusTypeSerial: NISysCfgBusType = 5;
pub const NISysCfgBusType_NISysCfgBusTypeTcpIp: NISysCfgBusType = 6;
pub const NISysCfgBusType_NISysCfgBusTypeCompactRio: NISysCfgBusType = 7;
pub const NISysCfgBusType_NISysCfgBusTypeScxi: NISysCfgBusType = 8;
pub const NISysCfgBusType_NISysCfgBusTypeCompactDaq: NISysCfgBusType = 9;
pub const NISysCfgBusType_NISysCfgBusTypeSwitchBlock: NISysCfgBusType = 10;
pub const NISysCfgBusType_NISysCfgBusTypeScc: NISysCfgBusType = 11;
pub const NISysCfgBusType_NISysCfgBusTypeFireWire: NISysCfgBusType = 12;
pub const NISysCfgBusType_NISysCfgBusTypeAccessory: NISysCfgBusType = 13;
pub const NISysCfgBusType_NISysCfgBusTypeCan: NISysCfgBusType = 14;
pub const NISysCfgBusType_NISysCfgBusTypeSwitchBlockDevice: NISysCfgBusType = 15;
pub type NISysCfgBusType = ::std::os::raw::c_int;
pub const NISysCfgHasDriverType_NISysCfgHasDriverTypeUnknown: NISysCfgHasDriverType = -1;
pub const NISysCfgHasDriverType_NISysCfgHasDriverTypeNotInstalled: NISysCfgHasDriverType = 0;
pub const NISysCfgHasDriverType_NISysCfgHasDriverTypeInstalled: NISysCfgHasDriverType = 1;
pub type NISysCfgHasDriverType = ::std::os::raw::c_int;
pub const NISysCfgIsPresentType_NISysCfgIsPresentTypeInitializing: NISysCfgIsPresentType = -2;
pub const NISysCfgIsPresentType_NISysCfgIsPresentTypeUnknown: NISysCfgIsPresentType = -1;
pub const NISysCfgIsPresentType_NISysCfgIsPresentTypeNotPresent: NISysCfgIsPresentType = 0;
pub const NISysCfgIsPresentType_NISysCfgIsPresentTypePresent: NISysCfgIsPresentType = 1;
pub type NISysCfgIsPresentType = ::std::os::raw::c_int;
pub const NISysCfgIpAddressMode_NISysCfgIpAddressModeStatic: NISysCfgIpAddressMode = 1;
pub const NISysCfgIpAddressMode_NISysCfgIpAddressModeDhcpOrLinkLocal: NISysCfgIpAddressMode = 2;
pub const NISysCfgIpAddressMode_NISysCfgIpAddressModeLinkLocalOnly: NISysCfgIpAddressMode = 4;
pub const NISysCfgIpAddressMode_NISysCfgIpAddressModeDhcpOnly: NISysCfgIpAddressMode = 8;
pub type NISysCfgIpAddressMode = ::std::os::raw::c_int;
pub const NISysCfgBool_NISysCfgBoolFalse: NISysCfgBool = 0;
pub const NISysCfgBool_NISysCfgBoolTrue: NISysCfgBool = 1;
pub type NISysCfgBool = ::std::os::raw::c_int;
pub const NISysCfgLocale_NISysCfgLocaleDefault: NISysCfgLocale = 0;
pub const NISysCfgLocale_NISysCfgLocaleChineseSimplified: NISysCfgLocale = 2052;
pub const NISysCfgLocale_NISysCfgLocaleEnglish: NISysCfgLocale = 1033;
pub const NISysCfgLocale_NISysCfgLocaleFrench: NISysCfgLocale = 1036;
pub const NISysCfgLocale_NISysCfgLocaleGerman: NISysCfgLocale = 1031;
pub const NISysCfgLocale_NISysCfgLocaleJapanese: NISysCfgLocale = 1041;
pub const NISysCfgLocale_NISysCfgLocaleKorean: NISysCfgLocale = 1042;
pub type NISysCfgLocale = ::std::os::raw::c_int;
pub const NISysCfgFilterMode_NISysCfgFilterModeMatchValuesAll: NISysCfgFilterMode = 1;
pub const NISysCfgFilterMode_NISysCfgFilterModeMatchValuesAny: NISysCfgFilterMode = 2;
pub const NISysCfgFilterMode_NISysCfgFilterModeMatchValuesNone: NISysCfgFilterMode = 3;
pub const NISysCfgFilterMode_NISysCfgFilterModeAllPropertiesExist: NISysCfgFilterMode = 4;
pub type NISysCfgFilterMode = ::std::os::raw::c_int;
pub const NISysCfgServiceType_NISysCfgServiceTypemDnsNiTcp: NISysCfgServiceType = 0;
pub const NISysCfgServiceType_NISysCfgServiceTypemDnsNiRealtime: NISysCfgServiceType = 1;
pub const NISysCfgServiceType_NISysCfgServiceTypemDnsNiSysapi: NISysCfgServiceType = 2;
pub const NISysCfgServiceType_NISysCfgServiceTypemDnsNiHttp: NISysCfgServiceType = 3;
pub const NISysCfgServiceType_NISysCfgServiceTypeLocalSystem: NISysCfgServiceType = 4;
pub const NISysCfgServiceType_NISysCfgServiceTypeLocalNetInterface: NISysCfgServiceType = 5;
pub const NISysCfgServiceType_NISysCfgServiceTypeLocalTimeKeeper: NISysCfgServiceType = 6;
pub const NISysCfgServiceType_NISysCfgServiceTypeLocalTimeSource: NISysCfgServiceType = 7;
pub const NISysCfgServiceType_NISysCfgServiceTypemDnsLxi: NISysCfgServiceType = 8;
pub const NISysCfgServiceType_NISysCfgServiceTypeLocalFpga: NISysCfgServiceType = 9;
pub type NISysCfgServiceType = ::std::os::raw::c_int;
pub const NISysCfgAdapterType_NISysCfgAdapterTypeEthernet: NISysCfgAdapterType = 1;
pub const NISysCfgAdapterType_NISysCfgAdapterTypeWlan: NISysCfgAdapterType = 2;
pub type NISysCfgAdapterType = ::std::os::raw::c_int;
pub const NISysCfgAdapterMode_NISysCfgAdapterModeDisabled: NISysCfgAdapterMode = 1;
pub const NISysCfgAdapterMode_NISysCfgAdapterModeTcpIpEthernet: NISysCfgAdapterMode = 2;
pub const NISysCfgAdapterMode_NISysCfgAdapterModeDeterministic: NISysCfgAdapterMode = 4;
pub const NISysCfgAdapterMode_NISysCfgAdapterModeEtherCat: NISysCfgAdapterMode = 8;
pub const NISysCfgAdapterMode_NISysCfgAdapterModeTcpIpWlan: NISysCfgAdapterMode = 32;
pub const NISysCfgAdapterMode_NISysCfgAdapterModeTcpIpAccessPoint: NISysCfgAdapterMode = 64;
pub type NISysCfgAdapterMode = ::std::os::raw::c_int;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedNone: NISysCfgLinkSpeed = 0;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedAuto: NISysCfgLinkSpeed = 1;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeed10mbHalf: NISysCfgLinkSpeed = 2;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeed10mbFull: NISysCfgLinkSpeed = 4;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeed100mbHalf: NISysCfgLinkSpeed = 8;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeed100mbFull: NISysCfgLinkSpeed = 16;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedGigabitHalf: NISysCfgLinkSpeed = 32;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedGigabitFull: NISysCfgLinkSpeed = 64;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedWlan80211a: NISysCfgLinkSpeed = 131072;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedWlan80211b: NISysCfgLinkSpeed = 262144;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedWlan80211g: NISysCfgLinkSpeed = 524288;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedWlan80211n: NISysCfgLinkSpeed = 1048576;
pub const NISysCfgLinkSpeed_NISysCfgLinkSpeedWlan80211n5GHz: NISysCfgLinkSpeed = 2097152;
pub type NISysCfgLinkSpeed = ::std::os::raw::c_int;
pub const NISysCfgPacketDetection_NISysCfgPacketDetectionNone: NISysCfgPacketDetection = 0;
pub const NISysCfgPacketDetection_NISysCfgPacketDetectionLineInterrupt: NISysCfgPacketDetection = 1;
pub const NISysCfgPacketDetection_NISysCfgPacketDetectionPolling: NISysCfgPacketDetection = 2;
pub const NISysCfgPacketDetection_NISysCfgPacketDetectionSignaledInterrupt:
    NISysCfgPacketDetection = 4;
pub type NISysCfgPacketDetection = ::std::os::raw::c_int;
pub const NISysCfgConnectionType_NISysCfgConnectionTypeNone: NISysCfgConnectionType = 0;
pub const NISysCfgConnectionType_NISysCfgConnectionTypeInfrastructure: NISysCfgConnectionType = 1;
pub const NISysCfgConnectionType_NISysCfgConnectionTypeAdHoc: NISysCfgConnectionType = 2;
pub type NISysCfgConnectionType = ::std::os::raw::c_int;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeNone: NISysCfgSecurityType = 0;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeNotSupported: NISysCfgSecurityType = 1;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeOpen: NISysCfgSecurityType = 2;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeWep: NISysCfgSecurityType = 4;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeWpaPsk: NISysCfgSecurityType = 8;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeWpaEap: NISysCfgSecurityType = 16;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeWpa2Psk: NISysCfgSecurityType = 32;
pub const NISysCfgSecurityType_NISysCfgSecurityTypeWpa2Eap: NISysCfgSecurityType = 64;
pub type NISysCfgSecurityType = ::std::os::raw::c_int;
pub const NISysCfgEapType_NISysCfgEapTypeNone: NISysCfgEapType = 0;
pub const NISysCfgEapType_NISysCfgEapTypeEapTls: NISysCfgEapType = 1;
pub const NISysCfgEapType_NISysCfgEapTypeEapTtls: NISysCfgEapType = 2;
pub const NISysCfgEapType_NISysCfgEapTypeEapFast: NISysCfgEapType = 4;
pub const NISysCfgEapType_NISysCfgEapTypeLeap: NISysCfgEapType = 8;
pub const NISysCfgEapType_NISysCfgEapTypePeap: NISysCfgEapType = 16;
pub type NISysCfgEapType = ::std::os::raw::c_int;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareReadyPendingAutoRestart: NISysCfgFirmwareStatus =
    -4;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareVerifyingNewImage: NISysCfgFirmwareStatus = -3;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareWritingFlashingNewImage: NISysCfgFirmwareStatus =
    -2;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareUpdateModeWaitingForImage: NISysCfgFirmwareStatus =
    -1;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareCorruptCannotRun: NISysCfgFirmwareStatus = 0;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareNoneInstalled: NISysCfgFirmwareStatus = 1;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareInstalledNormalOperation: NISysCfgFirmwareStatus =
    2;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareReadyPendingUserRestart: NISysCfgFirmwareStatus =
    3;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareReadyPendingUserAction: NISysCfgFirmwareStatus = 4;
pub const NISysCfgFirmwareStatus_NISysCfgFirmwareUpdateAttemptFailed: NISysCfgFirmwareStatus = 5;
pub type NISysCfgFirmwareStatus = ::std::os::raw::c_int;
pub const NISysCfgDeleteValidationMode_NISysCfgValidateButDoNotDelete:
    NISysCfgDeleteValidationMode = -1;
pub const NISysCfgDeleteValidationMode_NISysCfgDeleteIfNoDependenciesExist:
    NISysCfgDeleteValidationMode = 0;
pub const NISysCfgDeleteValidationMode_NISysCfgDeleteItemAndAnyDependencies:
    NISysCfgDeleteValidationMode = 1;
pub const NISysCfgDeleteValidationMode_NISysCfgDeleteItemButKeepDependencies:
    NISysCfgDeleteValidationMode = 2;
pub type NISysCfgDeleteValidationMode = ::std::os::raw::c_int;
pub const NISysCfgAccessType_NISysCfgAccessTypeLocalOnly: NISysCfgAccessType = 0;
pub const NISysCfgAccessType_NISysCfgAccessTypeLocalAndRemote: NISysCfgAccessType = 1;
pub type NISysCfgAccessType = ::std::os::raw::c_int;
pub const NISysCfgLedState_NISysCfgLedStateOff: NISysCfgLedState = 0;
pub const NISysCfgLedState_NISysCfgLedStateSolidGreen: NISysCfgLedState = 1;
pub const NISysCfgLedState_NISysCfgLedStateSolidYellow: NISysCfgLedState = 2;
pub const NISysCfgLedState_NISysCfgLedStateBlinkingGreen: NISysCfgLedState = 4;
pub const NISysCfgLedState_NISysCfgLedStateBlinkingYellow: NISysCfgLedState = 8;
pub type NISysCfgLedState = ::std::os::raw::c_int;
pub const NISysCfgSwitchState_NISysCfgSwitchStateDisabled: NISysCfgSwitchState = 0;
pub const NISysCfgSwitchState_NISysCfgSwitchStateEnabled: NISysCfgSwitchState = 1;
pub type NISysCfgSwitchState = ::std::os::raw::c_int;
pub const NISysCfgFirmwareUpdateMode_NISysCfgFirmwareUpdateModeNone: NISysCfgFirmwareUpdateMode = 0;
pub const NISysCfgFirmwareUpdateMode_NISysCfgFirmwareUpdateModeManual: NISysCfgFirmwareUpdateMode =
    1;
pub const NISysCfgFirmwareUpdateMode_NISysCfgFirmwareUpdateModeDriverManaged:
    NISysCfgFirmwareUpdateMode = 2;
pub type NISysCfgFirmwareUpdateMode = ::std::os::raw::c_int;
pub const NISysCfgModuleProgramMode_NISysCfgModuleProgramModeNone: NISysCfgModuleProgramMode = 0;
pub const NISysCfgModuleProgramMode_NISysCfgModuleProgramModeRealtimeCpu:
    NISysCfgModuleProgramMode = 1;
pub const NISysCfgModuleProgramMode_NISysCfgModuleProgramModeRealtimeScan:
    NISysCfgModuleProgramMode = 2;
pub const NISysCfgModuleProgramMode_NISysCfgModuleProgramModeLabVIEWFpga:
    NISysCfgModuleProgramMode = 4;
pub type NISysCfgModuleProgramMode = ::std::os::raw::c_int;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIsDevice: NISysCfgResourceProperty =
    16781312;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIsChassis: NISysCfgResourceProperty =
    16941056;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyConnectsToBusType:
    NISysCfgResourceProperty = 16785408;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyVendorId: NISysCfgResourceProperty =
    16789504;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyVendorName: NISysCfgResourceProperty =
    16793600;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyProductId: NISysCfgResourceProperty =
    16797696;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyProductName: NISysCfgResourceProperty =
    16801792;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySerialNumber: NISysCfgResourceProperty =
    16805888;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyFirmwareRevision:
    NISysCfgResourceProperty = 16969728;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIsNIProduct: NISysCfgResourceProperty =
    16809984;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIsSimulated: NISysCfgResourceProperty =
    16814080;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyConnectsToLinkName:
    NISysCfgResourceProperty = 16818176;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyHasDriver: NISysCfgResourceProperty =
    16920576;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIsPresent: NISysCfgResourceProperty =
    16924672;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySlotNumber: NISysCfgResourceProperty =
    16822272;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySupportsInternalCalibration:
    NISysCfgResourceProperty = 16842752;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyInternalCalibrationLastTime:
    NISysCfgResourceProperty = 16846848;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyInternalCalibrationLastTemp:
    NISysCfgResourceProperty = 16850944;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySupportsExternalCalibration:
    NISysCfgResourceProperty = 16859136;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyExternalCalibrationLastTemp:
    NISysCfgResourceProperty = 16867328;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCalibrationComments:
    NISysCfgResourceProperty = 16961536;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyInternalCalibrationLastLimited:
    NISysCfgResourceProperty = 17420288;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyExternalCalibrationChecksum:
    NISysCfgResourceProperty = 17432576;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCurrentTemp: NISysCfgResourceProperty =
    16965632;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyPxiPciBusNumber:
    NISysCfgResourceProperty = 16875520;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyPxiPciDeviceNumber:
    NISysCfgResourceProperty = 16879616;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyPxiPciFunctionNumber:
    NISysCfgResourceProperty = 16883712;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyPxiPciLinkWidth:
    NISysCfgResourceProperty = 16973824;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyPxiPciMaxLinkWidth:
    NISysCfgResourceProperty = 16977920;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyUsbInterface: NISysCfgResourceProperty =
    16887808;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpHostName: NISysCfgResourceProperty =
    16928768;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpMacAddress: NISysCfgResourceProperty =
    16986112;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpIpAddress: NISysCfgResourceProperty =
    16957440;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpDeviceClass:
    NISysCfgResourceProperty = 17022976;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyGpibPrimaryAddress:
    NISysCfgResourceProperty = 16994304;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyGpibSecondaryAddress:
    NISysCfgResourceProperty = 16998400;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySerialPortBinding:
    NISysCfgResourceProperty = 17076224;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyProvidesBusType:
    NISysCfgResourceProperty = 16932864;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyProvidesLinkName:
    NISysCfgResourceProperty = 16936960;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfSlots: NISysCfgResourceProperty =
    16826368;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySupportsFirmwareUpdate:
    NISysCfgResourceProperty = 17080320;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyFirmwareFilePattern:
    NISysCfgResourceProperty = 17084416;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyRecommendedCalibrationInterval:
    NISysCfgResourceProperty = 17207296;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySupportsCalibrationWrite:
    NISysCfgResourceProperty = 17215488;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyHardwareRevision:
    NISysCfgResourceProperty = 17256448;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCpuModelName: NISysCfgResourceProperty =
    17313792;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCpuSteppingRevision:
    NISysCfgResourceProperty = 17317888;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyModelNameNumber:
    NISysCfgResourceProperty = 17436672;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyModuleProgramMode:
    NISysCfgResourceProperty = 17440768;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyConnectsToNumSlots:
    NISysCfgResourceProperty = 17072128;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySlotOffsetLeft:
    NISysCfgResourceProperty = 17276928;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyInternalCalibrationValuesInRange:
    NISysCfgResourceProperty = 17489920;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyFirmwareUpdateMode:
    NISysCfgResourceProperty = 17354752;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyExternalCalibrationLastTime:
    NISysCfgResourceProperty = 16863232;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyRecommendedNextCalibrationTime:
    NISysCfgResourceProperty = 16871424;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyExternalCalibrationLastLimited:
    NISysCfgResourceProperty = 17428480;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCalibrationCurrentPassword:
    NISysCfgResourceProperty = 17223680;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCalibrationNewPassword:
    NISysCfgResourceProperty = 17227776;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySysCfgAccess: NISysCfgResourceProperty =
    219504640;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyAdapterType: NISysCfgResourceProperty =
    219332608;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyMacAddress: NISysCfgResourceProperty =
    219168768;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyAdapterMode: NISysCfgResourceProperty =
    219160576;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpIpRequestMode:
    NISysCfgResourceProperty = 219172864;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpIpv4Address:
    NISysCfgResourceProperty = 219181056;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpIpv4Subnet: NISysCfgResourceProperty =
    219189248;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpIpv4Gateway:
    NISysCfgResourceProperty = 219193344;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpIpv4DnsServer:
    NISysCfgResourceProperty = 219197440;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpPreferredLinkSpeed:
    NISysCfgResourceProperty = 219213824;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpCurrentLinkSpeed:
    NISysCfgResourceProperty = 219222016;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpPacketDetection:
    NISysCfgResourceProperty = 219258880;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTcpPollingInterval:
    NISysCfgResourceProperty = 219262976;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIsPrimaryAdapter:
    NISysCfgResourceProperty = 219308032;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyEtherCatMasterId:
    NISysCfgResourceProperty = 219250688;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyEtherCatMasterRedundancy:
    NISysCfgResourceProperty = 219500544;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanBssid: NISysCfgResourceProperty =
    219398144;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanCurrentLinkQuality:
    NISysCfgResourceProperty = 219394048;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanCurrentSsid:
    NISysCfgResourceProperty = 219377664;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanCurrentConnectionType:
    NISysCfgResourceProperty = 219381760;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanCurrentSecurityType:
    NISysCfgResourceProperty = 219385856;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanCurrentEapType:
    NISysCfgResourceProperty = 219389952;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanCountryCode:
    NISysCfgResourceProperty = 219406336;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanChannelNumber:
    NISysCfgResourceProperty = 219410432;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanClientCertificate:
    NISysCfgResourceProperty = 219422720;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanSecurityIdentity:
    NISysCfgResourceProperty = 219414528;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyWlanSecurityKey:
    NISysCfgResourceProperty = 219418624;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertySystemStartTime:
    NISysCfgResourceProperty = 17108992;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyCurrentTime: NISysCfgResourceProperty =
    219279360;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyTimeZone: NISysCfgResourceProperty =
    219471872;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyUserDirectedSafeModeSwitch:
    NISysCfgResourceProperty = 219537408;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyConsoleOutSwitch:
    NISysCfgResourceProperty = 219541504;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyIpResetSwitch: NISysCfgResourceProperty =
    219545600;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfDiscoveredAccessPoints:
    NISysCfgResourceProperty = 219365376;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfExperts:
    NISysCfgResourceProperty = 16891904;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfServices:
    NISysCfgResourceProperty = 17010688;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfAvailableFirmwareVersions:
    NISysCfgResourceProperty = 17088512;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfCpuCores:
    NISysCfgResourceProperty = 17506304;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfCpuLogicalProcessors:
    NISysCfgResourceProperty = 17137664;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfFans: NISysCfgResourceProperty =
    17174528;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfPowerSensors:
    NISysCfgResourceProperty = 17448960;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfTemperatureSensors:
    NISysCfgResourceProperty = 17186816;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfVoltageSensors:
    NISysCfgResourceProperty = 17149952;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfUserLedIndicators:
    NISysCfgResourceProperty = 17281024;
pub const NISysCfgResourceProperty_NISysCfgResourcePropertyNumberOfUserSwitches:
    NISysCfgResourceProperty = 17293312;
pub type NISysCfgResourceProperty = ::std::os::raw::c_int;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyServiceType: NISysCfgIndexedProperty =
    17014784;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyAvailableFirmwareVersion:
    NISysCfgIndexedProperty = 17092608;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableSsid:
    NISysCfgIndexedProperty = 219336704;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableBssid:
    NISysCfgIndexedProperty = 219443200;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableConnectionType:
    NISysCfgIndexedProperty = 219340800;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableSecurityType:
    NISysCfgIndexedProperty = 219344896;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableLinkQuality:
    NISysCfgIndexedProperty = 219353088;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableChannelNumber:
    NISysCfgIndexedProperty = 219357184;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyWlanAvailableLinkSpeed:
    NISysCfgIndexedProperty = 219361280;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyCpuTotalLoad: NISysCfgIndexedProperty =
    17141760;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyCpuInterruptLoad: NISysCfgIndexedProperty =
    17145856;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyCpuSpeed: NISysCfgIndexedProperty =
    17309696;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyFanName: NISysCfgIndexedProperty =
    17178624;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyFanReading: NISysCfgIndexedProperty =
    17182720;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyPowerName: NISysCfgIndexedProperty =
    17453056;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyPowerReading: NISysCfgIndexedProperty =
    17457152;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyPowerUpperCritical:
    NISysCfgIndexedProperty = 17461248;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyTemperatureName: NISysCfgIndexedProperty =
    17190912;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyTemperatureReading:
    NISysCfgIndexedProperty = 16965632;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyTemperatureLowerCritical:
    NISysCfgIndexedProperty = 17195008;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyTemperatureUpperCritical:
    NISysCfgIndexedProperty = 17199104;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyVoltageName: NISysCfgIndexedProperty =
    17154048;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyVoltageReading: NISysCfgIndexedProperty =
    17158144;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyVoltageNominal: NISysCfgIndexedProperty =
    17162240;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyVoltageLowerCritical:
    NISysCfgIndexedProperty = 17166336;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyVoltageUpperCritical:
    NISysCfgIndexedProperty = 17170432;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyUserLedName: NISysCfgIndexedProperty =
    17285120;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyUserSwitchName: NISysCfgIndexedProperty =
    17297408;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyUserSwitchState: NISysCfgIndexedProperty =
    17301504;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyUserLedState: NISysCfgIndexedProperty =
    17289216;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyExpertName: NISysCfgIndexedProperty =
    16900096;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyExpertResourceName:
    NISysCfgIndexedProperty = 16896000;
pub const NISysCfgIndexedProperty_NISysCfgIndexedPropertyExpertUserAlias: NISysCfgIndexedProperty =
    16904192;
pub type NISysCfgIndexedProperty = ::std::os::raw::c_int;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyDeviceClass: NISysCfgSystemProperty =
    16941057;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyProductId: NISysCfgSystemProperty = 16941058;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyFileSystem: NISysCfgSystemProperty =
    16941060;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyFirmwareRevision: NISysCfgSystemProperty =
    16941061;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsFactoryResetSupported:
    NISysCfgSystemProperty = 16941067;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsFirmwareUpdateSupported:
    NISysCfgSystemProperty = 16941068;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsLocked: NISysCfgSystemProperty = 16941069;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsLockingSupported: NISysCfgSystemProperty =
    16941070;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsOnLocalSubnet: NISysCfgSystemProperty =
    16941072;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsRestartSupported: NISysCfgSystemProperty =
    16941076;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyMacAddress: NISysCfgSystemProperty =
    16941077;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyProductName: NISysCfgSystemProperty =
    16941078;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyOperatingSystem: NISysCfgSystemProperty =
    16941079;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyOperatingSystemVersion:
    NISysCfgSystemProperty = 17100800;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyOperatingSystemDescription:
    NISysCfgSystemProperty = 17104896;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertySerialNumber: NISysCfgSystemProperty =
    16941080;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertySystemState: NISysCfgSystemProperty =
    16941082;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyMemoryPhysTotal: NISysCfgSystemProperty =
    219480064;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyMemoryPhysFree: NISysCfgSystemProperty =
    219484160;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyMemoryLargestBlock: NISysCfgSystemProperty =
    219488256;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyMemoryVirtTotal: NISysCfgSystemProperty =
    219492352;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyMemoryVirtFree: NISysCfgSystemProperty =
    219496448;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyPrimaryDiskTotal: NISysCfgSystemProperty =
    219291648;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyPrimaryDiskFree: NISysCfgSystemProperty =
    219295744;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertySystemResourceHandle:
    NISysCfgSystemProperty = 16941086;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyImageDescription: NISysCfgSystemProperty =
    219516928;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyImageId: NISysCfgSystemProperty = 219521024;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyImageTitle: NISysCfgSystemProperty =
    219525120;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyImageVersion: NISysCfgSystemProperty =
    219529216;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyInstalledApiVersion: NISysCfgSystemProperty =
    16941087;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsDst: NISysCfgSystemProperty = 16941066;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIsRestartProtected: NISysCfgSystemProperty =
    16941073;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyHaltOnError: NISysCfgSystemProperty =
    16941074;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyRepositoryLocation: NISysCfgSystemProperty =
    16941084;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertySystemComment: NISysCfgSystemProperty =
    16941081;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyAutoRestartTimeout: NISysCfgSystemProperty =
    16941085;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyDnsServer: NISysCfgSystemProperty = 16941059;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyGateway: NISysCfgSystemProperty = 16941062;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyHostname: NISysCfgSystemProperty = 16941063;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIpAddress: NISysCfgSystemProperty = 16941064;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertyIpAddressMode: NISysCfgSystemProperty =
    16941065;
pub const NISysCfgSystemProperty_NISysCfgSystemPropertySubnetMask: NISysCfgSystemProperty =
    16941083;
pub type NISysCfgSystemProperty = ::std::os::raw::c_int;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyIsDevice: NISysCfgFilterProperty = 16781312;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyIsChassis: NISysCfgFilterProperty = 16941056;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyServiceType: NISysCfgFilterProperty =
    17014784;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyConnectsToBusType: NISysCfgFilterProperty =
    16785408;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyConnectsToLinkName: NISysCfgFilterProperty =
    16818176;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyProvidesBusType: NISysCfgFilterProperty =
    16932864;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyVendorId: NISysCfgFilterProperty = 16789504;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyProductId: NISysCfgFilterProperty = 16797696;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertySerialNumber: NISysCfgFilterProperty =
    16805888;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyIsNIProduct: NISysCfgFilterProperty =
    16809984;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyIsSimulated: NISysCfgFilterProperty =
    16814080;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertySlotNumber: NISysCfgFilterProperty =
    16822272;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyHasDriver: NISysCfgFilterProperty = 16920576;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyIsPresent: NISysCfgFilterProperty = 16924672;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertySupportsCalibration: NISysCfgFilterProperty =
    16908288;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertySupportsFirmwareUpdate:
    NISysCfgFilterProperty = 17080320;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyProvidesLinkName: NISysCfgFilterProperty =
    16936960;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyExpertName: NISysCfgFilterProperty =
    16900096;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyResourceName: NISysCfgFilterProperty =
    16896000;
pub const NISysCfgFilterProperty_NISysCfgFilterPropertyUserAlias: NISysCfgFilterProperty = 16904192;
pub type NISysCfgFilterProperty = ::std::os::raw::c_int;
pub const NISysCfgPropertyType_NISysCfgPropertyTypeBool: NISysCfgPropertyType = 1;
pub const NISysCfgPropertyType_NISysCfgPropertyTypeInt: NISysCfgPropertyType = 2;
pub const NISysCfgPropertyType_NISysCfgPropertyTypeUnsignedInt: NISysCfgPropertyType = 3;
pub const NISysCfgPropertyType_NISysCfgPropertyTypeDouble: NISysCfgPropertyType = 4;
pub const NISysCfgPropertyType_NISysCfgPropertyTypeString: NISysCfgPropertyType = 6;
pub const NISysCfgPropertyType_NISysCfgPropertyTypeTimestamp: NISysCfgPropertyType = 7;
pub type NISysCfgPropertyType = ::std::os::raw::c_int;
extern "C" {
    #[doc = ""]
    pub fn NISysCfgInitializeSession(
        targetName: *const ::std::os::raw::c_char,
        username: *const ::std::os::raw::c_char,
        password: *const ::std::os::raw::c_char,
        language: NISysCfgLocale,
        forcePropertyRefresh: NISysCfgBool,
        connectTimeoutMsec: ::std::os::raw::c_uint,
        expertEnumHandle: *mut NISysCfgEnumExpertHandle,
        sessionHandle: *mut NISysCfgSessionHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgCloseHandle(syscfgHandle: *mut ::std::os::raw::c_void) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetSystemExperts(
        sessionHandle: NISysCfgSessionHandle,
        expertNames: *const ::std::os::raw::c_char,
        expertEnumHandle: *mut NISysCfgEnumExpertHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetRemoteTimeout(
        sessionHandle: NISysCfgSessionHandle,
        remoteTimeoutMsec: ::std::os::raw::c_uint,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgFindHardware(
        sessionHandle: NISysCfgSessionHandle,
        filterMode: NISysCfgFilterMode,
        filterHandle: NISysCfgFilterHandle,
        expertNames: *const ::std::os::raw::c_char,
        resourceEnumHandle: *mut NISysCfgEnumResourceHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgFindSystems(
        sessionHandle: NISysCfgSessionHandle,
        deviceClass: *const ::std::os::raw::c_char,
        detectOnlineSystems: NISysCfgBool,
        cacheMode: NISysCfgIncludeCachedResults,
        findOutputMode: NISysCfgSystemNameFormat,
        timeoutMsec: ::std::os::raw::c_uint,
        onlyInstallableSystems: NISysCfgBool,
        systemEnumHandle: *mut NISysCfgEnumSystemHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSelfTestHardware(
        resourceHandle: NISysCfgResourceHandle,
        mode: ::std::os::raw::c_uint,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSelfCalibrateHardware(
        resourceHandle: NISysCfgResourceHandle,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgResetHardware(
        resourceHandle: NISysCfgResourceHandle,
        mode: ::std::os::raw::c_uint,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgRenameResource(
        resourceHandle: NISysCfgResourceHandle,
        newName: *const ::std::os::raw::c_char,
        overwriteConflict: NISysCfgBool,
        updateDependencies: NISysCfgBool,
        nameAlreadyExisted: *mut NISysCfgBool,
        overwrittenResourceHandle: *mut NISysCfgResourceHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgDeleteResource(
        resourceHandle: NISysCfgResourceHandle,
        mode: NISysCfgDeleteValidationMode,
        dependentItemsDeleted: *mut NISysCfgBool,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetResourceProperty(
        resourceHandle: NISysCfgResourceHandle,
        propertyID: NISysCfgResourceProperty,
        value: *mut ::std::os::raw::c_void,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetResourceProperty(
        resourceHandle: NISysCfgResourceHandle,
        propertyID: NISysCfgResourceProperty,
        ...
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetResourcePropertyWithType(
        resourceHandle: NISysCfgResourceHandle,
        propertyID: NISysCfgResourceProperty,
        propertyType: NISysCfgPropertyType,
        ...
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetResourcePropertyV(
        resourceHandle: NISysCfgResourceHandle,
        propertyID: NISysCfgResourceProperty,
        args: va_list,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetResourcePropertyWithTypeV(
        resourceHandle: NISysCfgResourceHandle,
        propertyID: NISysCfgResourceProperty,
        propertyType: NISysCfgPropertyType,
        args: va_list,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetResourceIndexedProperty(
        resourceHandle: NISysCfgResourceHandle,
        propertyID: NISysCfgIndexedProperty,
        index: ::std::os::raw::c_uint,
        value: *mut ::std::os::raw::c_void,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSaveResourceChanges(
        resourceHandle: NISysCfgResourceHandle,
        changesRequireRestart: *mut NISysCfgBool,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetSystemProperty(
        sessionHandle: NISysCfgSessionHandle,
        propertyID: NISysCfgSystemProperty,
        value: *mut ::std::os::raw::c_void,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetSystemProperty(
        sessionHandle: NISysCfgSessionHandle,
        propertyID: NISysCfgSystemProperty,
        ...
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetSystemPropertyV(
        sessionHandle: NISysCfgSessionHandle,
        propertyID: NISysCfgSystemProperty,
        args: va_list,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSaveSystemChanges(
        sessionHandle: NISysCfgSessionHandle,
        changesRequireRestart: *mut NISysCfgBool,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgCreateFilter(
        sessionHandle: NISysCfgSessionHandle,
        filterHandle: *mut NISysCfgFilterHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetFilterProperty(
        filterHandle: NISysCfgFilterHandle,
        propertyID: NISysCfgFilterProperty,
        ...
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetFilterPropertyWithType(
        filterHandle: NISysCfgFilterHandle,
        propertyID: NISysCfgFilterProperty,
        propertyType: NISysCfgPropertyType,
        ...
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetFilterPropertyV(
        filterHandle: NISysCfgFilterHandle,
        propertyID: NISysCfgFilterProperty,
        args: va_list,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetFilterPropertyWithTypeV(
        filterHandle: NISysCfgFilterHandle,
        propertyID: NISysCfgFilterProperty,
        propertyType: NISysCfgPropertyType,
        args: va_list,
    ) -> NISysCfgStatus;
}
extern "C" {
    #[doc = ""]
    pub fn NISysCfgUpgradeFirmwareFromFile(
        resourceHandle: NISysCfgResourceHandle,
        firmwareFile: *const ::std::os::raw::c_char,
        autoStopTasks: NISysCfgBool,
        alwaysOverwrite: NISysCfgBool,
        waitForOperationToFinish: NISysCfgBool,
        firmwareStatus: *mut NISysCfgFirmwareStatus,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgUpgradeFirmwareVersion(
        resourceHandle: NISysCfgResourceHandle,
        firmwareVersion: *const ::std::os::raw::c_char,
        autoStopTasks: NISysCfgBool,
        alwaysOverwrite: NISysCfgBool,
        waitForOperationToFinish: NISysCfgBool,
        firmwareStatus: *mut NISysCfgFirmwareStatus,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgEraseFirmware(
        resourceHandle: NISysCfgResourceHandle,
        autoStopTasks: NISysCfgBool,
        firmwareStatus: *mut NISysCfgFirmwareStatus,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgCheckFirmwareStatus(
        resourceHandle: NISysCfgResourceHandle,
        percentComplete: *mut ::std::os::raw::c_int,
        firmwareStatus: *mut NISysCfgFirmwareStatus,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    #[doc = ""]
    pub fn NISysCfgFormat(
        sessionHandle: NISysCfgSessionHandle,
        forceSafeMode: NISysCfgBool,
        restartAfterFormat: NISysCfgBool,
        fileSystem: NISysCfgFileSystemMode,
        networkSettings: NISysCfgNetworkInterfaceSettings,
        timeoutMsec: ::std::os::raw::c_uint,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgFormatWithBaseSystemImage(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        fileSystem: NISysCfgFileSystemMode,
        networkSettings: NISysCfgNetworkInterfaceSettings,
        systemImageID: *const ::std::os::raw::c_char,
        systemImageVersion: *const ::std::os::raw::c_char,
        timeoutMsec: ::std::os::raw::c_uint,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgRestart(
        sessionHandle: NISysCfgSessionHandle,
        waitForRestartToFinish: NISysCfgBool,
        installMode: NISysCfgBool,
        flushDNS: NISysCfgBool,
        timeoutMsec: ::std::os::raw::c_uint,
        newIpAddress: *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetAvailableSoftwareComponents(
        sessionHandle: NISysCfgSessionHandle,
        itemTypes: NISysCfgIncludeComponentTypes,
        componentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetAvailableSoftwareSets(
        sessionHandle: NISysCfgSessionHandle,
        setEnumHandle: *mut NISysCfgEnumSoftwareSetHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetFilteredSoftwareComponents(
        repositoryPath: *const ::std::os::raw::c_char,
        deviceClass: *const ::std::os::raw::c_char,
        operatingSystem: *const ::std::os::raw::c_char,
        productID: ::std::os::raw::c_uint,
        itemTypes: NISysCfgIncludeComponentTypes,
        componentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetFilteredSoftwareSets(
        repositoryPath: *const ::std::os::raw::c_char,
        deviceClass: *const ::std::os::raw::c_char,
        operatingSystem: *const ::std::os::raw::c_char,
        productID: ::std::os::raw::c_uint,
        setEnumHandle: *mut NISysCfgEnumSoftwareSetHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetFilteredBaseSystemImages(
        repositoryPath: *const ::std::os::raw::c_char,
        deviceClass: *const ::std::os::raw::c_char,
        operatingSystem: *const ::std::os::raw::c_char,
        productID: ::std::os::raw::c_uint,
        systemImageEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetInstalledSoftwareComponents(
        sessionHandle: NISysCfgSessionHandle,
        itemTypes: NISysCfgIncludeComponentTypes,
        cached: NISysCfgBool,
        componentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetInstalledSoftwareSet(
        sessionHandle: NISysCfgSessionHandle,
        cached: NISysCfgBool,
        setHandle: *mut NISysCfgSoftwareSetHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetSystemImageAsFolder(
        sessionHandle: NISysCfgSessionHandle,
        destinationFolder: *const ::std::os::raw::c_char,
        encryptionPassphrase: *const ::std::os::raw::c_char,
        overwriteIfExists: NISysCfgBool,
        installedSoftwareOnly: NISysCfgBool,
        autoRestart: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetSystemImageAsFolder2(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        destinationFolder: *const ::std::os::raw::c_char,
        encryptionPassphrase: *const ::std::os::raw::c_char,
        numBlacklistEntries: ::std::os::raw::c_uint,
        blacklistFilesDirectories: *mut *const ::std::os::raw::c_char,
        overwriteIfExists: NISysCfgBool,
        installedSoftwareOnly: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgCreateSystemImageAsFolder(
        sessionHandle: NISysCfgSessionHandle,
        imageTitle: *const ::std::os::raw::c_char,
        imageID: *const ::std::os::raw::c_char,
        imageVersion: *const ::std::os::raw::c_char,
        imageDescription: *const ::std::os::raw::c_char,
        autoRestart: NISysCfgBool,
        destinationFolder: *const ::std::os::raw::c_char,
        encryptionPassphrase: *const ::std::os::raw::c_char,
        numBlacklistEntries: ::std::os::raw::c_uint,
        blacklistFilesDirectories: *mut *const ::std::os::raw::c_char,
        overwriteIfExists: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetSystemImageFromFolder(
        sessionHandle: NISysCfgSessionHandle,
        sourceFolder: *const ::std::os::raw::c_char,
        encryptionPassphrase: *const ::std::os::raw::c_char,
        autoRestart: NISysCfgBool,
        originalSystemOnly: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgSetSystemImageFromFolder2(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        sourceFolder: *const ::std::os::raw::c_char,
        encryptionPassphrase: *const ::std::os::raw::c_char,
        numBlacklistEntries: ::std::os::raw::c_uint,
        blacklistFilesDirectories: *mut *const ::std::os::raw::c_char,
        originalSystemOnly: NISysCfgBool,
        networkSettings: NISysCfgNetworkInterfaceSettings,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgInstallAll(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        deselectConflicts: NISysCfgBool,
        installedComponentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
        brokenDependencyEnumHandle: *mut NISysCfgEnumDependencyHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgInstallUninstallComponents(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        autoSelectDependencies: NISysCfgBool,
        componentToInstallEnumHandle: NISysCfgEnumSoftwareComponentHandle,
        numComponentsToUninstall: ::std::os::raw::c_uint,
        componentIDsToUninstall: *mut *const ::std::os::raw::c_char,
        brokenDependencyEnumHandle: *mut NISysCfgEnumDependencyHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgInstallUninstallComponents2(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        autoSelectDependencies: NISysCfgBool,
        autoSelectRecommends: NISysCfgBool,
        componentToInstallEnumHandle: NISysCfgEnumSoftwareComponentHandle,
        numComponentsToUninstall: ::std::os::raw::c_uint,
        componentIDsToUninstall: *mut *const ::std::os::raw::c_char,
        brokenDependencyEnumHandle: *mut NISysCfgEnumDependencyHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgInstallSoftwareSet(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        softwareSetID: *const ::std::os::raw::c_char,
        version: *const ::std::os::raw::c_char,
        addonEnumHandle: NISysCfgEnumSoftwareComponentHandle,
        brokenDependencyEnumHandle: *mut NISysCfgEnumDependencyHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgInstallStartup(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
        startupEnumHandle: NISysCfgEnumSoftwareComponentHandle,
        uninstallConflicts: NISysCfgBool,
        installedComponentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
        uninstalledComponentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
        brokenDependencyEnumHandle: *mut NISysCfgEnumDependencyHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgUninstallAll(
        sessionHandle: NISysCfgSessionHandle,
        autoRestart: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetSoftwareFeeds(
        sessionHandle: NISysCfgSessionHandle,
        feedEnumHandle: *mut NISysCfgEnumSoftwareFeedHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgAddSoftwareFeed(
        sessionHandle: NISysCfgSessionHandle,
        feedName: *const ::std::os::raw::c_char,
        uri: *const ::std::os::raw::c_char,
        enabled: NISysCfgBool,
        trusted: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgModifySoftwareFeed(
        sessionHandle: NISysCfgSessionHandle,
        feedName: *const ::std::os::raw::c_char,
        newFeedName: *const ::std::os::raw::c_char,
        uri: *const ::std::os::raw::c_char,
        enabled: NISysCfgBool,
        trusted: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgRemoveSoftwareFeed(
        sessionHandle: NISysCfgSessionHandle,
        feedName: *const ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    #[doc = ""]
    pub fn NISysCfgChangeAdministratorPassword(
        sessionHandle: NISysCfgSessionHandle,
        newPassword: *const ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgExportConfiguration(
        sessionHandle: NISysCfgSessionHandle,
        destinationFile: *const ::std::os::raw::c_char,
        expertNames: *const ::std::os::raw::c_char,
        overwriteIfExists: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgImportConfiguration(
        sessionHandle: NISysCfgSessionHandle,
        sourceFile: *const ::std::os::raw::c_char,
        expertNames: *const ::std::os::raw::c_char,
        importMode: NISysCfgImportMode,
        detailedResult: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGenerateMAXReport(
        sessionHandle: NISysCfgSessionHandle,
        outputFilename: *const ::std::os::raw::c_char,
        reportType: NISysCfgReportType,
        overwriteIfExists: NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgCreateComponentsEnum(
        componentEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgAddComponentToEnum(
        componentEnumHandle: NISysCfgEnumSoftwareComponentHandle,
        ID: *const ::std::os::raw::c_char,
        version: *const ::std::os::raw::c_char,
        mode: NISysCfgVersionSelectionMode,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgFreeDetailedString(str_: *mut ::std::os::raw::c_char) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextResource(
        sessionHandle: NISysCfgSessionHandle,
        resourceEnumHandle: NISysCfgEnumResourceHandle,
        resourceHandle: *mut NISysCfgResourceHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextSystemInfo(
        systemEnumHandle: NISysCfgEnumSystemHandle,
        system: *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextExpertInfo(
        expertEnumHandle: NISysCfgEnumExpertHandle,
        expertName: *mut ::std::os::raw::c_char,
        displayName: *mut ::std::os::raw::c_char,
        version: *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextComponentInfo(
        componentEnumHandle: NISysCfgEnumSoftwareComponentHandle,
        ID: *mut ::std::os::raw::c_char,
        version: *mut ::std::os::raw::c_char,
        title: *mut ::std::os::raw::c_char,
        itemType: *mut NISysCfgComponentType,
        detailedDescription: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextSoftwareSet(
        setEnumHandle: NISysCfgEnumSoftwareSetHandle,
        setHandle: *mut NISysCfgSoftwareSetHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetSoftwareSetInfo(
        setHandle: NISysCfgSoftwareSetHandle,
        itemTypes: NISysCfgIncludeComponentTypes,
        includeAddOnDeps: NISysCfgBool,
        ID: *mut ::std::os::raw::c_char,
        version: *mut ::std::os::raw::c_char,
        title: *mut ::std::os::raw::c_char,
        setType: *mut NISysCfgComponentType,
        detailedDescription: *mut *mut ::std::os::raw::c_char,
        addOnEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
        itemEnumHandle: *mut NISysCfgEnumSoftwareComponentHandle,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextDependencyInfo(
        dependencyEnumHandle: NISysCfgEnumDependencyHandle,
        dependerID: *mut ::std::os::raw::c_char,
        dependerVersion: *mut ::std::os::raw::c_char,
        dependerTitle: *mut ::std::os::raw::c_char,
        dependerDetailedDescription: *mut *mut ::std::os::raw::c_char,
        dependeeID: *mut ::std::os::raw::c_char,
        dependeeVersion: *mut ::std::os::raw::c_char,
        dependeeTitle: *mut ::std::os::raw::c_char,
        dependeeDetailedDescription: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgNextSoftwareFeed(
        feedEnumHandle: NISysCfgEnumSoftwareFeedHandle,
        feedName: *mut ::std::os::raw::c_char,
        uri: *mut ::std::os::raw::c_char,
        enabled: *mut NISysCfgBool,
        trusted: *mut NISysCfgBool,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgResetEnumeratorGetCount(
        enumHandle: *mut ::std::os::raw::c_void,
        count: *mut ::std::os::raw::c_uint,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgGetStatusDescription(
        sessionHandle: NISysCfgSessionHandle,
        status: NISysCfgStatus,
        detailedDescription: *mut *mut ::std::os::raw::c_char,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgTimestampFromValues(
        secondsSinceEpoch1970: NISysCfgUInt64,
        fractionalSeconds: f64,
        timestamp: *mut NISysCfgTimestampUTC,
    ) -> NISysCfgStatus;
}
extern "C" {
    pub fn NISysCfgValuesFromTimestamp(
        timestamp: *const NISysCfgTimestampUTC,
        secondsSinceEpoch1970: *mut NISysCfgUInt64,
        fractionalSeconds: *mut f64,
    ) -> NISysCfgStatus;
}
pub const NISysCfgControllerProperty_NISysCfgControllerPropertyMemoryModuleLocation:
    NISysCfgControllerProperty = 469807104;
pub const NISysCfgControllerProperty_NISysCfgControllerPropertyMemoryModuleModelName:
    NISysCfgControllerProperty = 469815296;
pub const NISysCfgControllerProperty_NISysCfgControllerPropertyMemoryModuleCapacity:
    NISysCfgControllerProperty = 469823488;
pub type NISysCfgControllerProperty = ::std::os::raw::c_int;
pub const NISysCfgPxiClock10Sources_NISysCfgPxiClk10SrcUnknown: NISysCfgPxiClock10Sources = -1;
pub const NISysCfgPxiClock10Sources_NISysCfgPxiClk10SrcInternal: NISysCfgPxiClock10Sources = 0;
pub const NISysCfgPxiClock10Sources_NISysCfgPxiClk10SrcBuiltInConnector: NISysCfgPxiClock10Sources =
    1;
pub const NISysCfgPxiClock10Sources_NISysCfgPxiClk10SrcTimingModule: NISysCfgPxiClock10Sources = 2;
pub const NISysCfgPxiClock10Sources_NISysCfgPxiClk10SrcTrig10MHzPort0: NISysCfgPxiClock10Sources =
    3;
pub type NISysCfgPxiClock10Sources = ::std::os::raw::c_int;
pub const NISysCfgPxiExternalClockOutputSource_NISysCfgPxiExternalClockOutputSourceUnknown:
    NISysCfgPxiExternalClockOutputSource = -1;
pub const NISysCfgPxiExternalClockOutputSource_NISysCfgPxiExternalClockOutputSourcePXI_CLK10:
    NISysCfgPxiExternalClockOutputSource = 0;
pub const NISysCfgPxiExternalClockOutputSource_NISysCfgPxiExternalClockOutputSourceInternalOscillator : NISysCfgPxiExternalClockOutputSource = 1 ;
pub type NISysCfgPxiExternalClockOutputSource = ::std::os::raw::c_int;
pub const NISysCfgPxiInternalOscillator_NISysCfgPxiInternalOscillatorUnsupported:
    NISysCfgPxiInternalOscillator = -1;
pub const NISysCfgPxiInternalOscillator_NISysCfgPxiInternalOscillatorVCXO:
    NISysCfgPxiInternalOscillator = 0;
pub const NISysCfgPxiInternalOscillator_NISysCfgPxiInternalOscillatorOCXO:
    NISysCfgPxiInternalOscillator = 1;
pub type NISysCfgPxiInternalOscillator = ::std::os::raw::c_int;
pub const NISysCfgPxiHighDensityTrigPortState_NISysCfgPxiHighDensityTrigPortStateDisconnected:
    NISysCfgPxiHighDensityTrigPortState = 0;
pub const NISysCfgPxiHighDensityTrigPortState_NISysCfgPxiHighDensityTrigPortStateConnected:
    NISysCfgPxiHighDensityTrigPortState = 1;
pub const NISysCfgPxiHighDensityTrigPortState_NISysCfgPxiHighDensityTrigPortStateConnectedUnknown : NISysCfgPxiHighDensityTrigPortState = 2 ;
pub const NISysCfgPxiHighDensityTrigPortState_NISysCfgPxiHighDensityTrigPortStateLoopback:
    NISysCfgPxiHighDensityTrigPortState = 3;
pub type NISysCfgPxiHighDensityTrigPortState = ::std::os::raw::c_int;
pub const NISysCfgPxiFanModes_NISysCfgPxiFanModesAuto: NISysCfgPxiFanModes = 1;
pub const NISysCfgPxiFanModes_NISysCfgPxiFanModesSafeManual: NISysCfgPxiFanModes = 2;
pub const NISysCfgPxiFanModes_NISysCfgPxiFanModesHigh: NISysCfgPxiFanModes = 4;
pub type NISysCfgPxiFanModes = ::std::os::raw::c_int;
pub const NISysCfgPxiCoolingProfiles_NISysCfgPxiCoolingProfile38W: NISysCfgPxiCoolingProfiles = 1;
pub const NISysCfgPxiCoolingProfiles_NISysCfgPxiCoolingProfile58W: NISysCfgPxiCoolingProfiles = 2;
pub const NISysCfgPxiCoolingProfiles_NISysCfgPxiCoolingProfile82W: NISysCfgPxiCoolingProfiles = 4;
pub type NISysCfgPxiCoolingProfiles = ::std::os::raw::c_int;
pub const NISysCfgPxiCoolingProfileSource_NISysCfgPxiCoolingProfileSourceUnknown:
    NISysCfgPxiCoolingProfileSource = -1;
pub const NISysCfgPxiCoolingProfileSource_NISysCfgPxiCoolingProfileSourceUserSpecified:
    NISysCfgPxiCoolingProfileSource = 1;
pub const NISysCfgPxiCoolingProfileSource_NISysCfgPxiCoolingProfileSourceModuleRequest:
    NISysCfgPxiCoolingProfileSource = 2;
pub const NISysCfgPxiCoolingProfileSource_NISysCfgPxiCoolingProfileSourceUserOverrideOfModuleRequest : NISysCfgPxiCoolingProfileSource = 3 ;
pub type NISysCfgPxiCoolingProfileSource = ::std::os::raw::c_int;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateOff: NISysCfgPxiPowerSupplyState =
    0;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateOn: NISysCfgPxiPowerSupplyState =
    1;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFaulted:
    NISysCfgPxiPowerSupplyState = 2;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_OutputVoltageOvervoltage12V : NISysCfgPxiPowerSupplyState = 16 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_OutputVoltageUndervoltage12V : NISysCfgPxiPowerSupplyState = 17 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_OutputVoltageOvervoltage5VAux : NISysCfgPxiPowerSupplyState = 18 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_OutputVoltageUndervoltage5VAux : NISysCfgPxiPowerSupplyState = 19 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_OutputCurrentOvercurrent12V : NISysCfgPxiPowerSupplyState = 20 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_OutputCurrentOvercurrent5VAux : NISysCfgPxiPowerSupplyState = 21 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_InputVoltageOvervoltage:
    NISysCfgPxiPowerSupplyState = 22;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_InputVoltageUndervoltage:
    NISysCfgPxiPowerSupplyState = 23;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_LowerAmbientTemperature:
    NISysCfgPxiPowerSupplyState = 24;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_UpperAmbientTemperature:
    NISysCfgPxiPowerSupplyState = 25;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_LowerInternalTemperature:
    NISysCfgPxiPowerSupplyState = 26;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_UpperInternalTemperature:
    NISysCfgPxiPowerSupplyState = 27;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateFault_Fan:
    NISysCfgPxiPowerSupplyState = 28;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputVoltageOvervoltage12V : NISysCfgPxiPowerSupplyState = 48 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputVoltageUndervoltage12V : NISysCfgPxiPowerSupplyState = 49 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputVoltageOvervoltage5VAux : NISysCfgPxiPowerSupplyState = 50 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputVoltageUndervoltage5VAux : NISysCfgPxiPowerSupplyState = 51 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputCurrentOvercurrent12V : NISysCfgPxiPowerSupplyState = 52 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputCurrentOvercurrent5VAux : NISysCfgPxiPowerSupplyState = 53 ;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_OutputCurrentSharing:
    NISysCfgPxiPowerSupplyState = 54;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_InputVoltageOvervoltage:
    NISysCfgPxiPowerSupplyState = 55;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_InputVoltageUndervoltage:
    NISysCfgPxiPowerSupplyState = 56;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_LowerAmbientTemperature:
    NISysCfgPxiPowerSupplyState = 57;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_UpperAmbientTemperature:
    NISysCfgPxiPowerSupplyState = 58;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_LowerInternalTemperature:
    NISysCfgPxiPowerSupplyState = 59;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_UpperInternalTemperature:
    NISysCfgPxiPowerSupplyState = 60;
pub const NISysCfgPxiPowerSupplyState_NISysCfgPxiPowerSupplyStateAlert_Fan:
    NISysCfgPxiPowerSupplyState = 61;
pub type NISysCfgPxiPowerSupplyState = ::std::os::raw::c_int;
pub const NISysCfgPxiInhibitModes_NISysCfgPxiInhibitDefault: NISysCfgPxiInhibitModes = 1;
pub const NISysCfgPxiInhibitModes_NISysCfgPxiInhibitManual: NISysCfgPxiInhibitModes = 2;
pub type NISysCfgPxiInhibitModes = ::std::os::raw::c_int;
pub const NISysCfgPxiCalExtActions_NISysCfgPxiCalExtCancel: NISysCfgPxiCalExtActions = 0;
pub const NISysCfgPxiCalExtActions_NISysCfgPxiCalExtOcxoStart: NISysCfgPxiCalExtActions = 1;
pub const NISysCfgPxiCalExtActions_NISysCfgPxiCalExtCommit: NISysCfgPxiCalExtActions = 2;
pub type NISysCfgPxiCalExtActions = ::std::os::raw::c_int;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Chassis_Controlled : NISysCfgPxiChassisLedBlinkPatterns = 1 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_One_Blink:
    NISysCfgPxiChassisLedBlinkPatterns = 2;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Blink_Blink_Blink : NISysCfgPxiChassisLedBlinkPatterns = 4 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Blink_Blink_Steady : NISysCfgPxiChassisLedBlinkPatterns = 8 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Blink_Steady_Blink : NISysCfgPxiChassisLedBlinkPatterns = 16 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Blink_Steady_Steady : NISysCfgPxiChassisLedBlinkPatterns = 32 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Steady_Blink_Blink : NISysCfgPxiChassisLedBlinkPatterns = 64 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Steady_Blink_Steady : NISysCfgPxiChassisLedBlinkPatterns = 128 ;
pub const NISysCfgPxiChassisLedBlinkPatterns_NISysCfgPxiChassisLedBlinkPattern_Three_Steady_Steady_Blink : NISysCfgPxiChassisLedBlinkPatterns = 256 ;
pub type NISysCfgPxiChassisLedBlinkPatterns = ::std::os::raw::c_int;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyPxiChassisNumber: NISysCfgPxiProperty = 184565760;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyChassisLedBlinkPattern: NISysCfgPxiProperty =
    184655872;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyClk10Source: NISysCfgPxiProperty = 184635392;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyExternalClockOutputSource: NISysCfgPxiProperty =
    184639488;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyInternalOscillator: NISysCfgPxiProperty =
    184643584;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyHighDensityTrigPortCount: NISysCfgPxiProperty =
    200286208;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyFanMode: NISysCfgPxiProperty = 185597952;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyFanUserRpm: NISysCfgPxiProperty = 185602048;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertySupportedFanModes: NISysCfgPxiProperty = 185606144;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyFanManualRpmLowerBound: NISysCfgPxiProperty =
    185634816;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyFanManualRpmUpperBound: NISysCfgPxiProperty =
    185638912;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyCoolingProfile: NISysCfgPxiProperty = 185610240;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyCoolingProfileSource: NISysCfgPxiProperty =
    185663488;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertySupportedCoolingProfiles: NISysCfgPxiProperty =
    185614336;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyEnableUserOverrideOfCoolingProfile:
    NISysCfgPxiProperty = 185659392;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyPowerSupplyBayCount: NISysCfgPxiProperty =
    186777600;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyPowerSuppliesRedundant: NISysCfgPxiProperty =
    186798080;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyInhibitMode: NISysCfgPxiProperty = 186806272;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertySupportedInhibitModes: NISysCfgPxiProperty =
    186810368;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyCalExtAction: NISysCfgPxiProperty = 186908672;
pub const NISysCfgPxiProperty_NISysCfgPxiPropertyCalExtDacValue: NISysCfgPxiProperty = 186925056;
pub type NISysCfgPxiProperty = ::std::os::raw::c_int;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyPowerSupplyName:
    NISysCfgPxiIndexedProperty = 186781696;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyPowerSupplyState:
    NISysCfgPxiIndexedProperty = 186789888;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyPowerSupplyPower:
    NISysCfgPxiIndexedProperty = 186793984;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyPowerSupplyPowerReading:
    NISysCfgPxiIndexedProperty = 186822656;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyPowerSupplyIntakeTemp:
    NISysCfgPxiIndexedProperty = 186802176;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyPowerSupplyPowerLineFrequency:
    NISysCfgPxiIndexedProperty = 186785792;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyHighDensityTrigPortName:
    NISysCfgPxiIndexedProperty = 200290304;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyHighDensityTrigPortState:
    NISysCfgPxiIndexedProperty = 200294400;
pub const NISysCfgPxiIndexedProperty_NISysCfgPxiIndexedPropertyHighDensityTrigPortRemoteDeviceAlias : NISysCfgPxiIndexedProperty = 200298496 ;
pub type NISysCfgPxiIndexedProperty = ::std::os::raw::c_int;
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
